import React from 'react'

type AnimatedGradientBorderProps = {
  children: React.ReactNode
  className?: string
  gradientColors?: string[]
  borderWidth?: number
  borderRadius?: number
  innerBorderRadius?: number
  innerBackground?: string
  durationMs?: number
}

function AnimatedGradientBorder({
  children,
  className,
  gradientColors = ['#EBF8FC', '#7FB8EF', '#15FFAB', '#00C2FF'],
  borderWidth = 2,
  borderRadius = 14,
  innerBorderRadius = 12,
  innerBackground = 'rgba(10, 18, 25, 0.98)',
  durationMs = 3200,
}: AnimatedGradientBorderProps) {
  const gradient = `conic-gradient(from 180deg, ${gradientColors.join(', ')})`

  return (
    <>
      <style>{`
        @keyframes vistarAgSpin {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }

        @media (prefers-reduced-motion: reduce) {
          .vistarAgBorder::before { animation: none !important; }
        }

        .vistarAgBorder {
          position: relative;
          border-radius: var(--vistar-ag-borderRadius);
          overflow: hidden;
        }

        .vistarAgBorder::before {
          content: '';
          position: absolute;
          inset: 0;
          border-radius: var(--vistar-ag-borderRadius);
          background: var(--vistar-ag-gradient);
          animation: vistarAgSpin var(--vistar-ag-duration) linear infinite;
          will-change: transform;
          z-index: 0;
        }

        .vistarAgBorder::after {
          content: '';
          position: absolute;
          inset: var(--vistar-ag-borderWidth);
          border-radius: var(--vistar-ag-innerBorderRadius);
          background: var(--vistar-ag-innerBackground);
          z-index: 1;
        }

        .vistarAgContent {
          position: relative;
          z-index: 2;
        }
      `}</style>

      <div
        className={['vistarAgBorder', className].filter(Boolean).join(' ')}
        style={
          {
            ['--vistar-ag-gradient' as any]: gradient,
            ['--vistar-ag-duration' as any]: `${durationMs}ms`,
            ['--vistar-ag-borderWidth' as any]: `${borderWidth}px`,
            ['--vistar-ag-borderRadius' as any]: `${borderRadius}px`,
            ['--vistar-ag-innerBorderRadius' as any]: `${innerBorderRadius}px`,
            ['--vistar-ag-innerBackground' as any]: innerBackground,
          } as React.CSSProperties
        }
      >
        <div className="vistarAgContent">{children}</div>
      </div>
    </>
  )
}

export type VistarAnimatedTopCardProps = {
  metricValue?: string
  unit?: string
  leftCaption?: string
  companyName?: string
  features?: string[]
  viewAllLabel?: string
  className?: string
  cardWidth?: number | string
  cardHeight?: number | string
}

// This is a single, reusable test component with ONLY the animated rotating gradient border.
// You can import `VistarAnimatedTopCard` into any React/Vite project to validate the animation + layout.
export default function VistarAnimatedTopCard({
  metricValue = '08.02',
  unit = 'Cr',
  leftCaption = 'Total value generated by Vistaar',
  companyName = 'Vistaar',
  features = [
    '+75% cost saving rate',
    'AI recommendation can improve output by 6%',
    'AI identified 3 critical leakage areas today',
  ],
  viewAllLabel = 'View all',
  className,
  cardWidth = 804,
  cardHeight = 146,
}: VistarAnimatedTopCardProps) {
  return (
    <AnimatedGradientBorder
      className={className}
      gradientColors={['#EBF8FC', '#7FB8EF', '#15FFAB', '#00C2FF']}
      borderWidth={2}
      borderRadius={14}
      innerBorderRadius={12}
      innerBackground={'rgba(30, 32, 40, 0.95)'}
      durationMs={3200}
    >
      <div
        style={{
          width: cardWidth,
          height: cardHeight,
          padding: '12px 16px',
          display: 'flex',
          gap: 16,
          alignItems: 'stretch',
          color: '#EBEBEB',
          fontFamily:
            'ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, "Apple Color Emoji", "Segoe UI Emoji"',
        }}
      >
        <div
          style={{
            width: 320,
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'space-between',
          }}
        >
          <div
            style={{
              borderRadius: 12,
              background: 'rgba(55, 57, 66, 0.55)',
              border: '1px solid rgba(255,255,255,0.12)',
              padding: '12px 14px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              gap: 10,
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <div
                style={{
                  width: 36,
                  height: 36,
                  borderRadius: 10,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  background: 'rgba(30, 32, 40, 0.9)',
                  border: '1px solid rgba(255,255,255,0.08)',
                  fontWeight: 700,
                }}
                aria-hidden="true"
              >
                ⇄
              </div>
              <div style={{ lineHeight: 1 }}>
                <div style={{ fontSize: 28, fontWeight: 800, letterSpacing: 0.2 }}>{metricValue}</div>
                <div style={{ fontSize: 12, opacity: 0.8, marginTop: 2 }}>{unit}</div>
              </div>
            </div>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: 10, opacity: 0.85 }}>
            <span style={{ fontSize: 12 }}>{leftCaption}</span>
            <span
              style={{
                fontSize: 12,
                fontWeight: 700,
                padding: '2px 10px',
                borderRadius: 999,
                background: 'rgba(21, 255, 171, 0.12)',
                color: '#15FFAB',
              }}
            >
              {companyName}
            </span>
          </div>
        </div>

        <div
          style={{
            flex: 1,
            display: 'flex',
            alignItems: 'flex-start',
            justifyContent: 'space-between',
            gap: 16,
            paddingTop: 6,
          }}
        >
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {features.slice(0, 3).map((f, idx) => (
              <div key={idx} style={{ display: 'flex', alignItems: 'center', gap: 10, fontSize: 12, opacity: 0.9 }}>
                <span
                  aria-hidden="true"
                  style={{
                    width: 16,
                    height: 16,
                    borderRadius: 6,
                    display: 'inline-flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    background:
                      idx === 0
                        ? 'rgba(21, 255, 171, 0.14)'
                        : idx === 1
                          ? 'rgba(0, 194, 255, 0.14)'
                          : 'rgba(127, 184, 239, 0.12)',
                    color:
                      idx === 0 ? '#15FFAB' : idx === 1 ? '#00C2FF' : '#7FB8EF',
                    border: '1px solid rgba(255,255,255,0.08)',
                    fontSize: 10,
                    fontWeight: 800,
                  }}
                >
                  {idx === 0 ? '↘' : idx === 1 ? '✦' : '⟡'}
                </span>
                <span>{f}</span>
              </div>
            ))}
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end' }}>
            <div style={{ fontSize: 12, opacity: 0.85, marginTop: 6, color: '#A9A9B7' }}>
              {/*
                In the Figma screenshot, "View all" sits on the right side of the top row.
                Keep it simple here; you can make it a link/button in your app.
              */}
              {viewAllLabel}
            </div>
          </div>
        </div>
      </div>
    </AnimatedGradientBorder>
  )
}

